name: Johannes Rieke
title: Johannes Rieke
logo: /profile.jpg
description: Master student in computational neuroscience at Technical University Berlin & Bernstein Center for Computational Neuroscience Berlin. Interested in deep learning & neuroscience.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
