remote_theme: nickbalestra/kactus

name: "Johannes Rieke"
description: "Product Engineer @ Streamlit"
meta_description: "Johannes Rieke's website"

aboutPage: true

markdown: kramdown
highlighter: rouge

plugins: [jekyll-paginate]
paginate: 50
domain_name: "https://www.jrieke.com"
google_analytics: "UA-128373902-1"
disqus: false

# Details for the RSS feed generator
url: "https://www.jrieke.com"
author: "Johannes Rieke"
authorTwitter: "jrieke"

permalink: /:year/:title/

defaults:
  - scope:
      path: "" # empty string for all files
      type: pages
    values:
      layout: default
  - scope:
      path: "" # empty string for all files
      type: posts
    values:
      layout: post
  - scope:
      path: ""
      type: drafts
    values:
      layout: post
