name: Johannes Rieke
title: Johannes Rieke
description: Master student in computational neuroscience at Technical University Berlin & Bernstein Center for Computational Neuroscience Berlin. Interested in deep learning & neuroscience.
show_downloads: false
google_analytics:
remote-theme: kactus

markdown: kramdown
highlighter: rouge

plugins: [jekyll-paginate]
paginate: 20
disqus: false
