
remote_theme: nickbalestra/kactus

name: "Johannes Rieke"
description: "Master student in computational neuroscience at Technical University Berlin & Bernstein Center for Computational Neuroscience Berlin"
meta_description: "Johannes Rieke's website"

aboutPage: true

markdown: kramdown
highlighter: rouge

plugins: [jekyll-paginate]
paginate: 50
domain_name: 'http://jrieke.github.io'
google_analytics: 'UA-XXXXXXXX-X'
disqus: false

# Details for the RSS feed generator
url:            'http://jrieke.github.io'
author:         'Johannes Rieke'
authorTwitter:  'jrieke'

permalink:       /:year/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
